# Generated by Django 3.0.3 on 2021-12-30 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_name',
            field=models.CharField(choices=[('GENERAL', 'General'), ('LARAVEL', 'Laravel'), ('PYTHON', 'Python'), ('VUE', 'Vue'), ('ANGULAR', 'Angular'), ('PHP', 'Php')], default='GENERAL', max_length=254, unique=True),
        ),
    ]
