# Generated by Django 3.0.3 on 2022-01-12 22:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_auto_20211230_1214'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_skill',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
