# Generated by Django 3.0.3 on 2021-12-26 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0002_auto_20211226_1932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_status',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
    ]
