# Generated by Django 3.0.3 on 2021-12-27 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0004_auto_20211227_0646'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experience',
            name='educational_or_working',
        ),
        migrations.AddField(
            model_name='experience',
            name='is_educational',
            field=models.BooleanField(default=True),
        ),
    ]
