# Generated by Django 3.0.3 on 2021-12-27 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0005_auto_20211227_0650'),
    ]

    operations = [
        migrations.RenameField(
            model_name='experience',
            old_name='is_educational',
            new_name='is_working',
        ),
    ]
