# Generated by Django 3.0.3 on 2021-12-28 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0007_auto_20211227_1857'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Experience',
        ),
    ]
