# Generated by Django 3.0.3 on 2021-12-28 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('is_working', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=253, unique=True)),
                ('organization_name', models.CharField(max_length=253)),
                ('from_date', models.DateField()),
                ('to_date', models.DateField(blank=True, default=None, null=True)),
                ('description', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
