name: Django Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.8  # Replace with the desired Python version

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Deploy Django
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DEPLOY_HOST }}  # Replace with your deployment server's IP or hostname
          username: ${{ secrets.DEPLOY_USERNAME }}  # Replace with your SSH username
          key: ${{ secrets.DEPLOY_SSH_KEY }}  # Replace with your SSH password or use SSH key authentication
          script: |
            cd /var/www/vhosts/naveedshahzad
            git pull origin main  # Update the code
            su - naveed
            cd /var/www/vhosts/naveedshahzad
            source env/bin/activate # Go to environment 
            python manage.py migrate  # Apply database migrations
            logout
            sudo systemctl restart gunicorn  # Restart Gunicorn (or any other WSGI server)
